# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rspec', '~> 3.4'
gem 'sinatra', '~> 1.4', '>= 1.4.7'

# gem "rails"
